# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CensusVis2022Dialog
                                 A QGIS plugin
 Fetch and Visualize Census Data 2022
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-08-29
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Ardavan Sassani
        email                : a.sassani@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.core import Qgis
from qgis.PyQt.QtCore import QThread

# from PyQt5.QtCore import QThread

import os
import sys
import json
import pandas as pd
from multiprocessing import Process

from .config.config_manager import ConfigurationManager
from .data import file_download_path
from .cencus_downloader import CensusDownloader
from .SettingsDialog import SettingsDialog
from .nlp.panel import get_relevant_variables_nltk

# from .pyqt_file_downloader import DownloadWidget

CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))

CENCUS_API_BASE_URL = (
    f"https://api.census.gov/data/2022/pdb/tract?for=tract:*&get=GIDTR,"
)
SHAPE_API_BASE_URL = "https://www2.census.gov/geo/tiger/TIGER2020/TRACT/"

FORM_CLASS_MAIN, _ = uic.loadUiType(
    os.path.join(CURRENT_DIR, "CenVis2022_dialog_base.ui")
)

STATE_READY = "ready"
STATE_DOWNLOADING = "downloading"
STATE_DONE = "done"


class CenVis2022Dialog(QtWidgets.QDialog, FORM_CLASS_MAIN):
    def __init__(self, parent=None, plugin_instance=None, config_mng:ConfigurationManager=None):
        """Constructor."""
        super(CenVis2022Dialog, self).__init__(parent)
        self.plugin_instance = plugin_instance
        self.config_mng:ConfigurationManager = config_mng
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.census_data = []
        self.setupUi(self)
        self.items = {}
        self.state = STATE_READY

        self.us_states = pd.read_json(
            f"{CURRENT_DIR}/constants/us_counties.json", dtype=False
        )

        self.btnDownload.clicked.connect(self.onDownload)
        self.btnSettings.clicked.connect(self.onSettingsDialog)
        self.lstVariablesList.itemSelectionChanged.connect(self.onItemListChange)
        self.cbState.currentIndexChanged.connect(self.onStateChange)
        self.cbCounty.currentIndexChanged.connect(self.onCountyChange)
        self.btnGetItems.clicked.connect(self.get_items)

        self.btnTest.clicked.connect(self.onTest)

        self.init_states()

    def onItemListChange(self):
        self.onChangeAnything()

    def onStateChange(self):
        self.init_counties()

    def onCountyChange(self):
        self.onChangeAnything()

    def get_items(self):
        self.items = get_relevant_variables_nltk(self.txtQuery.toPlainText())
        self.lstVariablesList.clear()
        self.lstVariablesList.addItems(self.items.keys())

    def onSettingsDialog(self):
        settings_dialog = SettingsDialog(self, config_mng=self.config_mng)
        _ = settings_dialog.exec_()

    def onDownload(self):
        self.state = STATE_DOWNLOADING
        self.census_data = []
        state_fips = self.cbState.currentData()
        county_fips = self.cbCounty.currentData()
        county_filter_string = f"&in=county:{county_fips}"
        if self.chbAllCounties.isChecked():
            county_fips = "all"
            county_filter_string = ""
        
        self.btnDownload.setText("Downloading...")
        self.btnDownload.setEnabled(False)
        for item in self.lstVariablesList.selectedItems():
            variable_tag = self.items[item.text()]
            census_file = f"{self.config_mng.settings.data_path}/census_data/{state_fips}/{county_fips}/{variable_tag}.json"
            census_url = f"{CENCUS_API_BASE_URL}{variable_tag}&in=state:{state_fips}{county_filter_string}&key={self.config_mng.settings.census_api_key}"
            self.census_data.append((census_url, census_file))

        shape_file = (
            f"{self.config_mng.settings.data_path}/shapes_files/tl_2020_{state_fips}_tract.zip"
        )
        shape_url = f"{SHAPE_API_BASE_URL}tl_2020_{state_fips}_tract.zip"
        self.census_data.append((shape_url, shape_file))

        self.download_thread = QThread()
        self.downloader = CensusDownloader(self.census_data)
        self.downloader.moveToThread(self.download_thread)

        self.download_thread.started.connect(self.downloader.run)
        self.downloader.finished.connect(self.download_thread.quit)
        self.downloader.finished.connect(self.downloader.deleteLater)
        self.download_thread.finished.connect(self.download_thread.deleteLater)

        self.downloader.progress.connect(self.update_progress)
        self.downloader.finished.connect(self.download_finished)

        self.download_thread.start()

    def update_progress(self, current, total):
        percentage = int((current / total) * 100)
        self.progressBar.setValue(percentage)
        self.plugin_instance.iface.messageBar().pushInfo(
            "Census Downloader", f"Progress: {percentage}%"
        )

    def download_finished(self, results):
        self.state = STATE_DONE
        self.btnDownload.setText("Done!")
        self.btnDownload.setEnabled(True)
        self.btnDownload.clicked.disconnect()
        self.btnDownload.clicked.connect(self.accept)

    def init_states(self):
        for state in self.us_states.iterrows():
            self.cbState.addItem(state[1]["name"], state[1]["fips"])
        self.init_counties()

    def init_counties(self):
        self.cbCounty.clear()
        state_fips = self.cbState.currentData()
        counties = self.us_states[self.us_states["fips"] == state_fips]["counties"]
        for county in counties.iloc[0]:
            self.cbCounty.addItem(county["name"], county["fips"])

    def onChangeAnything(self):
        if self.state != STATE_READY:
            self.btnDownload.setText("Download")
            self.btnDownload.clicked.disconnect()
            self.btnDownload.clicked.connect(self.onDownload)
            self.btnDownload.setEnabled(True)
            self.state = STATE_READY
        # print("Something Changed")

    def onTest(self):
        # if len(self.lstVariablesList.selectedItems()) == 0:
        #     self.plugin_instance.iface.messageBar().pushMessage(
        #         "Census Downloader",
        #         "At least one variable should be selected.",
        #         level=Qgis.Critical, duration=20)
        #     return
        try:
            self.plugin_instance.testFunctionAtPlugin(
                self.cbState.currentData(),
                self.cbCounty.currentData(),
                [
                    self.items[item.text()]
                    for item in self.lstVariablesList.selectedItems()
                ],
            )
            # self.plugin_instance.iface.messageBar().pushMessage("Census Downloader", "Test2", level=Qgis.Success)
        except Exception as e:
            print("Error", e)
